language: node_js
node_js:
  - "fir-45436"
script:
 - npm run build
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project projectId --token $FIREBASE_TOKEN