language: node_js
node_js:
  - "10.16.0"
script:
 - npm install
 - npm run build
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project $projectId --token $FIREBASE_TOKEN